site_name: Site-78 Legal Codex
site_url: https://site-78.github.io/
theme:
  name: material
  palette:
    scheme: slate
  font:
    text: Electrolize
    code: Courier Prime 
  features:
    - navigation.footer
    - navigation.tracking
    - toc.follow
  favicon: assets/SCPF_Logo.png
plugins:   
  - search
  - meta
  - tags
markdown_extensions:
  - attr_list
  - pymdownx.mark
  - admonition
  - pymdownx.details
  - md_in_html
  - toc:
      title: On this page 
      permalink: true 
      toc_depth: 6
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/
copyright: Copyright &copy; - Site-78 2025
extra_css:
  - assets/stylesheets/extra.css
